# Generated by Django 5.1.8 on 2025-05-07 14:19

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('is_tenant_admin', models.BooleanField(default=False, help_text='Designates whether the user can manage other users in this tenant.', verbose_name='tenant admin status')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='must change password')),
                ('last_password_change', models.DateTimeField(auto_now_add=True, verbose_name='last password change')),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenant Users',
                'db_table': 'staff_tenantuser',
            },
            bases=('public.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
