# Generated by Django 5.1.8 on 2025-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='grace_period_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_employees',
            field=models.PositiveIntegerField(default=10, help_text='Maximum employees allowed on payroll.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=1, help_text='Maximum users allowed to access the system.'),
        ),
    ]
