# Generated by Django 5.1.8 on 2025-05-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTenantSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('subdomain', models.CharField(max_length=63)),
                ('admin_full_name', models.CharField(max_length=150)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password_encrypted', models.CharField(max_length=255)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.plan')),
            ],
            options={
                'verbose_name': 'Pending Tenant Signup',
                'indexes': [models.Index(fields=['subdomain'], name='onboarding__subdoma_26192f_idx'), models.Index(fields=['admin_email'], name='onboarding__admin_e_98765a_idx')],
            },
        ),
    ]
